// USER

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const ADD_DEVICE_USER = 'ADD_DEVICE_USER';
export const ADD_DEVICE_USER_SUCCESS = 'ADD_DEVICE_USER_SUCCESS';
export const ADD_DEVICE_USER_ERROR = 'ADD_DEVICE_USER_ERROR';

export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_ERROR = 'GET_USER_BY_ID_ERROR';

// COURSE

export const GET_COURSE_TEACHER = 'GET_COURSE_TEACHER';
export const GET_COURSE_TEACHER_SUCCESS = 'GET_COURSE_TEACHER_SUCCESS';
export const GET_COURSE_TEACHER_ERROR = 'GET_COURSE_TEACHER_ERROR';

// SCHEDULE

export const GET_SCHEDULE = 'GET_SCHEDULE';
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS';
export const GET_SCHEDULE_ERROR = 'GET_SCHEDULE_ERROR';

// TEACHER

export const GET_EQUIPMENT_STUDENT = 'GET_EQUIPMENT_STUDENT';
export const GET_EQUIPMENT_STUDENT_SUCCESS = 'GET_EQUIPMENT_STUDENT_SUCCESS';
export const GET_EQUIPMENT_STUDENT_ERROR = 'GET_EQUIPMENT_STUDENT_ERROR';

export const GET_STUDENT_BY_SCHEDULE = 'GET_STUDENT_BY_SCHEDULE';
export const GET_STUDENT_BY_SCHEDULE_SUCCESS =
  'GET_STUDENT_BY_SCHEDULE_SUCCESS';
export const GET_STUDENT_BY_SCHEDULE_ERROR = 'GET_STUDENT_BY_SCHEDULE_ERROR';

export const ATTENDANCE_STUDENT_BY_TEACHER = 'ATTENDANCE_STUDENT_BY_TEACHER';
export const ATTENDANCE_STUDENT_BY_TEACHER_SUCCESS =
  'ATTENDANCE_STUDENT_BY_TEACHER_SUCCESS';
export const ATTENDANCE_STUDENT_BY_TEACHER_ERROR =
  'ATTENDANCE_STUDENT_BY_TEACHER_ERROR';

export const CREATE_REPO = 'CREATE_REPO';
export const CREATE_REPO_SUCCESS = 'CREATE_REPO_SUCCESS';
export const CREATE_REPO_ERROR = 'CREATE_REPO_ERROR';
